# Secret Manager bills per *active secret version* ($0.06/version/month, first
# 6 free) — not per byte, and one version holds up to 64 KiB. So the
# hand-managed credentials ship as a single JSON blob instead of one secret
# each, which keeps the project inside the free tier. The backend splices the
# blob back into a flat env map at startup (see `backend/src/fx/env.ts`), so
# application code still reads plain `TMDB_API_KEY`-style keys.
#
# Two secrets, deliberately — not one:
#
#   APP_SECRETS  JSON object of `app_secret_keys` below. Terraform creates the
#                secret but never the *value*: populate out-of-band so the
#                credentials never land in Terraform state (see bootstrap.sh).
#   MONGO_URL    Generated by Terraform itself (`atlas.tf` splices the random
#                DB password into the Atlas SRV host), so folding it into the
#                blob would drag all the others into state to build it.

locals {
  # Keys expected inside the APP_SECRETS JSON object. Terraform neither reads
  # nor writes their values — this list drives `terraform output` and the
  # populate helper in bootstrap.sh.
  app_secret_keys = [
    # Notion OAuth — one client_id + client_secret per distro
    "NOTION_TMDB_CLIENT_ID",
    "NOTION_TMDB_CLIENT_SECRET",
    "NOTION_IGDB_CLIENT_ID",
    "NOTION_IGDB_CLIENT_SECRET",
    "NOTION_GBOOK_CLIENT_ID",
    "NOTION_GBOOK_CLIENT_SECRET",
    "NOTION_BILLETREDUC_CLIENT_ID",
    "NOTION_BILLETREDUC_CLIENT_SECRET",
    "NOTION_BACKUP_CLIENT_ID",
    "NOTION_BACKUP_CLIENT_SECRET",
    "NOTION_GOCARDLESS_CLIENT_ID",
    "NOTION_GOCARDLESS_CLIENT_SECRET",
    # Third-party API credentials
    "TMDB_API_KEY",
    "IGDB_CLIENT_ID",
    "IGDB_CLIENT_SECRET",
    "GOCARDLESS_ID",
    "GOCARDLESS_SECRET",
  ]
}

resource "google_secret_manager_secret" "app_secrets" {
  secret_id = "APP_SECRETS"

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret" "mongo_url" {
  secret_id = "MONGO_URL"

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

# MONGO_URL predates the consolidation as `secret["MONGO_URL"]` — rename the
# state address instead of destroying and recreating the secret.
moved {
  from = google_secret_manager_secret.secret["MONGO_URL"]
  to   = google_secret_manager_secret.mongo_url
}

# Runtime service account can read both secrets.
#
# The map keys are written out as literals rather than derived from
# `.secret_id`: for_each keys must be known at plan time, and an attribute of a
# not-yet-created resource is unknown, which fails the whole plan. Only the
# values may depend on apply-time results. Keying on the secret name also keeps
# the pre-consolidation `runtime_can_read["MONGO_URL"]` binding in place.
resource "google_secret_manager_secret_iam_member" "runtime_can_read" {
  for_each = {
    APP_SECRETS = google_secret_manager_secret.app_secrets.secret_id
    MONGO_URL   = google_secret_manager_secret.mongo_url.secret_id
  }
  secret_id = each.value
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}
