name: Run checks on every commits of this repo

on:
  push:
    branches:
      - "**"

env: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          npm install

      - name: "Run linter"
        shell: bash
        if: always()
        run: |
          npm run lint

      - name: "Run format checker"
        shell: bash
        if: always()
        run: |
          npx prettier --check .

      - name: Run frontend compilation
        shell: bash
        if: always()
        run: |
          npm --workspace frontend run build

      - name: Run backend compilation
        shell: bash
        if: always()
        run: |
          npm --workspace backend run build
