# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - notion-tmdb-fr

on:
  push:
    branches:
      - main
  workflow_dispatch:

env: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          npm install
          npm run build --workspaces

      - name: "Create dist"
        shell: bash
        run: |
          node --loader ts-node/esm/transpile-only support/build.ts
          cd dist
          npm prune --workspace backend --omit dev

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Create secret .env file"
        shell: bash
        env:
          ENVIRONMENT_VARIABLES: ${{ secrets.ENVIRONMENT_VARIABLES }}
        run: |
          echo "$ENVIRONMENT_VARIABLES" >> .env

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "notion-tmdb-fr"
          slot-name: "Production"
          package: "."
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_34EFEBDB6A7040FDB5D3AD2CDF1ED704 }}
